theme: jekyll-theme-slate
# Site settings
title: =0                     #你博客的标题
SEOTitle: =0的博客        #显示在浏览器上搜索的时候显示的标题
email: You@gmail.com    
description: "个人技术笔记"              #网站介绍
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://dengyuning.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
[测试](www.baidu.com)
